server:
  port: 8081
  servlet:
    context-path: /be/javapostgre
spring:
  application:
    name: java_postgre
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://94.237.78.111:5432/postgres
    username: postgres
    password: postgres123
    driverClassName: org.postgresql.Driver
management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: /actuator/health